//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressionEngine.Renderer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressionEngine.Renderer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command requires {0} parameters. {1} was given..
        /// </summary>
        internal static string ErrorArgumentCount {
            get {
                return ResourceManager.GetString("ErrorArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command requires at least {0} parameters. {1} was given..
        /// </summary>
        internal static string ErrorArgumentCountMin {
            get {
                return ResourceManager.GetString("ErrorArgumentCountMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t modify or delete a constant value..
        /// </summary>
        internal static string ErrorConstantWriteDelete {
            get {
                return ResourceManager.GetString("ErrorConstantWriteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty command.
        /// </summary>
        internal static string ErrorEmptyCommand {
            get {
                return ResourceManager.GetString("ErrorEmptyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t evaluate: {0}.
        /// </summary>
        internal static string ErrorEvaluate {
            get {
                return ResourceManager.GetString("ErrorEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can&apos;t be parsed to type: {0}.
        /// </summary>
        internal static string ErrorParsing {
            get {
                return ResourceManager.GetString("ErrorParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: {0}.
        /// </summary>
        internal static string ErrorUnknownCommand {
            get {
                return ResourceManager.GetString("ErrorUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown mode: {0}.
        /// </summary>
        internal static string ErrorUnknownMode {
            get {
                return ResourceManager.GetString("ErrorUnknownMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown variable: {0}.
        /// </summary>
        internal static string ErrorUnknownVariable {
            get {
                return ResourceManager.GetString("ErrorUnknownVariable", resourceCulture);
            }
        }
    }
}
