//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressionEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressionEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified expression can&apos;t be differentiated.
        /// </summary>
        internal static string CanotDifferentiate {
            get {
                return ResourceManager.GetString("CanotDifferentiate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a constant. Constant values can&apos;t be redefined.
        /// </summary>
        internal static string ConstantCantReassign {
            get {
                return ResourceManager.GetString("ConstantCantReassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide by zero detected in function.
        /// </summary>
        internal static string DivideByZero {
            get {
                return ResourceManager.GetString("DivideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse an empty function.
        /// </summary>
        internal static string EmptyFunction {
            get {
                return ResourceManager.GetString("EmptyFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected exponent, got: {0}.
        /// </summary>
        internal static string ExpectedExponent {
            get {
                return ResourceManager.GetString("ExpectedExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression after + or - operator.
        /// </summary>
        internal static string ExpectedExpression {
            get {
                return ResourceManager.GetString("ExpectedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression after ^ operator.
        /// </summary>
        internal static string ExpectedExpressionAfterExponent {
            get {
                return ResourceManager.GetString("ExpectedExpressionAfterExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression after * or / operator.
        /// </summary>
        internal static string ExpectedExpressionAfterMultDiv {
            get {
                return ResourceManager.GetString("ExpectedExpressionAfterMultDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected mult or divide, got: {0}.
        /// </summary>
        internal static string ExpectedMultiplyDivide {
            get {
                return ResourceManager.GetString("ExpectedMultiplyDivide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected plus or minus, got: {0}.
        /// </summary>
        internal static string ExpectedPlussminus {
            get {
                return ResourceManager.GetString("ExpectedPlussminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested function isn&apos;t  representable with the given number of variables.
        /// </summary>
        internal static string FunctionRequiresMoreVariables {
            get {
                return ResourceManager.GetString("FunctionRequiresMoreVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The from value must be smaller than the to value.
        /// </summary>
        internal static string IntegrateErrorRange {
            get {
                return ResourceManager.GetString("IntegrateErrorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression.
        /// </summary>
        internal static string InvalidExpression {
            get {
                return ResourceManager.GetString("InvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps must be at least 2 and an even number.
        /// </summary>
        internal static string InvalidSteps {
            get {
                return ResourceManager.GetString("InvalidSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token &apos;{0}&apos; in function: {1}.
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing:.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only supported on logic expressions..
        /// </summary>
        internal static string NotLogicExpression {
            get {
                return ResourceManager.GetString("NotLogicExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables not set on expression..
        /// </summary>
        internal static string NoVariables {
            get {
                return ResourceManager.GetString("NoVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t complete operation on expression. Varaibles are not set.
        /// </summary>
        internal static string NoVariableValues {
            get {
                return ResourceManager.GetString("NoVariableValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Number sytem has to be between 2 and 36.
        /// </summary>
        internal static string NumberSystemRangeError {
            get {
                return ResourceManager.GetString("NumberSystemRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed past the end of the function.
        /// </summary>
        internal static string OutOfTokens {
            get {
                return ResourceManager.GetString("OutOfTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 24 variables are supported.
        /// </summary>
        internal static string ToManyVariables {
            get {
                return ResourceManager.GetString("ToManyVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing characters: {0}.
        /// </summary>
        internal static string TrailingChars {
            get {
                return ResourceManager.GetString("TrailingChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token in Factor: {0}.
        /// </summary>
        internal static string UnexpectedTokenInFactior {
            get {
                return ResourceManager.GetString("UnexpectedTokenInFactior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown function: {0}.
        /// </summary>
        internal static string UnknownFuction {
            get {
                return ResourceManager.GetString("UnknownFuction", resourceCulture);
            }
        }
    }
}
