name: Create release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version number'
        default: ''
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: echo check version
      run: |
        echo ${{ github.event.inputs.versionName }} | grep -oE '^([0-9]){1,4}\.([0-9]){1,2}\.([0-9]){1,2}\.([0-9]){1,2}$' -
        echo "Package version will be ${{ github.event.inputs.versionName }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ExpressionEngine.sln
      
    - name: Build
      run: dotnet build ExpressionEngine.sln --nologo --no-restore --configuration Release -p:Version=${{ github.event.inputs.versionName }}
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Create nuget package
      run: dotnet pack ExpressionEngine.sln --configuration Release
    
    - name: Ensure GitHub NuGet Source
      run: |
        dotnet nuget add source ${{ env.NUGET_URL }} \
        -n github \
        -u ${GITHUB_TOKEN} \
        -p ${GITHUB_USER} \
        --store-password-in-clear-text
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USER: ${{ secrets.TOKEN}}
    
    - name: Push nuget packages
      run: dotnet nuget push ./bin/Release/*.nupkg --source "github" --skip-duplicate --no-symbols true
      
    - name: cleanup
      if: allways()
      continue-on-error: true
      run: dotnet nuget remove source github

    