name: Create release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version number'
        default: ''
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: echo check version
      run: |
        echo ${{ github.event.inputs.versionName }} | grep -oE '^([0-9]){1,4}\.([0-9]){1,2}\.([0-9]){1,2}\.([0-9]){1,2}$' -
        echo "Package version will be ${{ github.event.inputs.versionName }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ExpressionEngine.sln
      
    - name: Build
      run: dotnet build ExpressionEngine.sln --nologo --no-restore --configuration Release -p:Version=${{ github.event.inputs.versionName }}
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Create nuget package
      run: dotnet pack ExpressionEngine.sln --configuration Release
    
    - name: Setup Github Package registry tool
      run: dotnet tool install --global --verbosity minimal --no-cache gpr
    
    - name: Push nuget packages
      run: |
        gpr push \
        --api-key ${{ secrets.PACKAGE_TOKEN }} \
        --repository ${{ github.repository }} \
        --retries 3 \
        ./bin/Release/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        
    - name: Create tag
      run: |
        git tag ${{ github.event.inputs.versionName }}"
        git push origin --tags

    