name: Create release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version number'
        default: ''
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: echo check version
      run: |
        echo ${{ github.event.inputs.versionName }} | grep -oE '^([0-9]){1,4}\.([0-9]){1,2}\.([0-9]){1,2}\.([0-9]){1,2}$' -
        echo "Package version will be ${{ github.event.inputs.versionName }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ExpressionEngine.sln --no-cache
      
    - name: Build
      run: dotnet build ExpressionEngine.sln --nologo --no-restore --configuration Release -p:Version=${{ github.event.inputs.versionName }}
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Create nuget package
      run: dotnet pack ExpressionEngine.sln --configuration Release --no-build -p:PackageVersion=${{ github.event.inputs.versionName }}
    
    - name: Push nuget packages
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/webmaster442/index.json -n github
        dotnet nuget push ./bin/Release/*.nupkg -s github -k $NUGET_AUTH_TOKEN --skip-duplicate --no-symbols true
        dotnet nuget remove source github
      env:
         NUGET_AUTH_TOKEN: ${{ github.token }}
      
    - name: cleanup
      run: dotnet nuget remove source github

    