name: Create release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version number'
        default: ''
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo version
      run: echo "Package version will be ${{ github.event.inputs.versionName }}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ExpressionEngine.sln
      
    - name: Build
      run: dotnet build ExpressionEngine.sln --no-restore --configuration Release -p:Version=${{ github.event.inputs.versionName }}
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
